//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 使用者 ycIDE.rc

#define IDS_APP_TITLE			103

#define IDR_MAINFRAME			128
#define IDD_YCIDE_DIALOG	102
#define IDD_ABOUTBOX			103
#define IDM_ABOUT				104
#define IDM_EXIT				105
#define IDM_NEW					106
#define IDM_OPEN				107
#define IDM_SAVE				108
#define IDM_SAVE_AS				109
#define IDM_OPEN_FOLDER			110
#define IDM_CLOSE_FOLDER		111
#define IDM_NEW_PROJECT			126
#define IDM_OPEN_PROJECT		127
#define IDM_CLOSE_PROJECT		128
#define IDM_ADD_FILE_TO_PROJECT	129
#define IDM_FILE				115
#define IDM_HELP				116
#define IDM_THEME				117
#define IDM_THEME_DARK			118
#define IDM_THEME_LIGHT			119
#define IDM_THEME_CUSTOM		120
#define IDD_THEME_CONFIG		121
#define IDM_TOOLS				122
#define IDM_SYSTEM_CONFIG		123
#define IDM_LIBRARY_CONFIG		124
#define IDD_LIBRARY_CONFIG		125

// 插入菜单项
#define IDM_INSERT				130
#define IDM_INSERT_MODULE		131
#define IDM_INSERT_DLL_COMMAND	132
#define IDM_INSERT_DATATYPE		133
#define IDM_INSERT_GLOBAL_VAR	134
#define IDM_INSERT_CONSTANT		135
#define IDM_INSERT_WINDOW		136
#define IDM_INSERT_CLASS_MODULE	137

#define IDI_YCIDE			112
#define IDI_SMALL				113
#define IDC_YCIDE			114
#define IDC_MYICON				2
#ifndef IDC_STATIC
#define IDC_STATIC				-1
#endif
// 新对象的下一组默认值
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NO_MFC					130
#define _APS_NEXT_RESOURCE_VALUE	129
#define _APS_NEXT_COMMAND_VALUE		32771
#define _APS_NEXT_CONTROL_VALUE		1000
#define _APS_NEXT_SYMED_VALUE		110
#endif
#endif
